{
 "title": "ProxySQL Fleet Overview",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "env",
    "label": "Env",
    "query": {
     "query": "query_result(proxysql_client_connections_total)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "query_result(proxysql_client_connections_total{env=\"$env\"})"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "query_result(proxysql_client_connections_total{cluster=\"$cluster\"})"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "query_result(proxysql_client_connections_total{namespace=\"$namespace\"})"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "query_result(proxysql_client_connections_total{job=\"$job\"})"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1s,5s,30s,1m,5m,15m,1h,6h,1d,7d,15d"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Active Transactions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(proxysql_active_transactions{pod=\"$pod\", namespace=\"$namespace\", job=\"$job\", env=\"$env\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Frontend Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "proxysql_client_connections_connected{pod=\"$pod\", namespace=\"$namespace\", job=\"$job\", env=\"$env\", cluster=\"$cluster\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Frontend Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "proxysql_client_connections_connected{pod=\"$pod\", namespace=\"$namespace\", job=\"$job\", env=\"$env\", cluster=\"$cluster\"}/proxysql_mysql_max_connections{pod=\"$pod\", namespace=\"$namespace\", job=\"$job\", env=\"$env\", cluster=\"$cluster\"}*100",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Backend Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 7, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "proxysql_server_connections_connected{pod=\"$pod\", namespace=\"$namespace\", job=\"$job\", env=\"$env\", cluster=\"$cluster\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Frontend vs. Backend Ratio",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100-(sum(proxysql_connpool_conns{pod=\"$pod\", namespace=\"$namespace\", job=\"$job\", env=\"$env\", cluster=\"$cluster\",status=\"used\"})/sum(proxysql_client_connections_connected{pod=\"$pod\", namespace=\"$namespace\", job=\"$job\", env=\"$env\", cluster=\"$cluster\"})*100)",
     "legendFormat": "Multiplexing Efficiency Ratio"
    }
   ]
  },
  {
   "title": "Frontend Connection Overview",
   "type": "graph",
   "gridPos": { "h": 13, "w": 17, "x": 7, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "proxysql_client_connections_non_idle{pod=\"$pod\", namespace=\"$namespace\", job=\"$job\", env=\"$env\", cluster=\"$cluster\"}",
     "legendFormat": "{{job}} (used)"
    },
    {
     "expr": "proxysql_client_connections_connected{pod=\"$pod\", namespace=\"$namespace\", job=\"$job\", env=\"$env\", cluster=\"$cluster\"}-proxysql_client_connections_non_idle{pod=\"$pod\", namespace=\"$namespace\", job=\"$job\", env=\"$env\", cluster=\"$cluster\"}",
     "legendFormat": "{{job}} (idle)"
    }
   ]
  },
  {
   "title": "Connection Overview",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(proxysql_client_connections_connected{pod=\"$pod\", namespace=\"$namespace\", job=\"$job\", env=\"$env\", cluster=\"$cluster\"})",
     "legendFormat": "Total Frontend Connections"
    },
    {
     "expr": "sum(proxysql_connpool_conns{pod=\"$pod\", namespace=\"$namespace\", job=\"$job\", env=\"$env\", cluster=\"$cluster\",status=\"used\"})",
     "legendFormat": "Total Backend Connections (in-use)"
    },
    {
     "expr": "sum(proxysql_connpool_conns{pod=\"$pod\", namespace=\"$namespace\", job=\"$job\", env=\"$env\", cluster=\"$cluster\",status=\"free\"})",
     "legendFormat": "Total Backend Connections (free)"
    }
   ]
  },
  {
   "title": "Total Send / Receive Rates",
   "type": "stat",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(proxysql_queries_frontends_bytes_total{pod=\"$pod\", namespace=\"$namespace\", job=\"$job\", env=\"$env\", cluster=\"$cluster\",traffic_flow=\"sent\"}[$__rate_interval]))",
     "legendFormat": "Frontend Send Rate"
    },
    {
     "expr": "sum(irate(proxysql_queries_frontends_bytes_total{traffic_flow=\"received\",pod=\"$pod\", namespace=\"$namespace\", job=\"$job\", env=\"$env\", cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Frontend Receive Rate"
    },
    {
     "expr": "sum(irate(proxysql_queries_backends_bytes_total{traffic_flow=\"sent\",pod=\"$pod\", namespace=\"$namespace\", job=\"$job\", env=\"$env\", cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Backend Send Rate"
    },
    {
     "expr": "sum(irate(proxysql_queries_backends_bytes_total{traffic_flow=\"received\",pod=\"$pod\", namespace=\"$namespace\", job=\"$job\", env=\"$env\", cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Backend Receive Rate"
    }
   ]
  },
  {
   "title": "Backend Connection Overview",
   "type": "graph",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(proxysql_connpool_conns{pod=\"$pod\", namespace=\"$namespace\", job=\"$job\", env=\"$env\", cluster=\"$cluster\",status=\"used\"}) by (endpoint)",
     "legendFormat": "{{endpoint}} (used)"
    },
    {
     "expr": "sum(proxysql_connpool_conns{pod=\"$pod\", namespace=\"$namespace\", job=\"$job\", env=\"$env\", cluster=\"$cluster\",status=\"free\"}) by (endpoint)",
     "legendFormat": "{{endpoint}} (free)"
    }
   ]
  }
 ]
}